/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Analizadores.A_Sintactico;
import Analizadores.Analizador_Lexico;
import Clases.Controlador;
import java.io.BufferedReader;
import java.io.StringReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Mafe
 */
public class Seguimiento extends javax.swing.JFrame {

    Analizador_Lexico lexico;
    A_Sintactico sintactico;

    /**
     * Creates new form Seguimiento
     */
    public Seguimiento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPlay = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCargar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonVerificar = new javax.swing.JButton();
        jButtonEjecutar = new javax.swing.JButton();
        jLabeleditor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaCambioVariables = new javax.swing.JTextArea();
        variables = new javax.swing.JLabel();
        ambientes = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        Adelantar = new javax.swing.JButton();
        Atrasar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaAlgoritmo = new javax.swing.JTextArea();
        algoritmo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play.png"))); // NOI18N
        jButtonPlay.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButton1.setText("Ir Modo Juego");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPequeño.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seguimiento de Algoritmos ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 30));

        jButtonCargar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCargar.setText("Cargar");
        getContentPane().add(jButtonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuardar.setText("Guardar");
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jButtonVerificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVerificar.setText("Verificar");
        getContentPane().add(jButtonVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jButtonEjecutar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonEjecutar.setText("Ejecutar");
        jButtonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        jLabeleditor.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabeleditor.setText("Campo Editor Algoritmo ");
        getContentPane().add(jLabeleditor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        AreaCambioVariables.setColumns(20);
        AreaCambioVariables.setRows(5);
        jScrollPane1.setViewportView(AreaCambioVariables);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 350, 190));

        variables.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        variables.setForeground(new java.awt.Color(255, 255, 255));
        variables.setText("Estado variables y parametros usados");
        getContentPane().add(variables, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        ambientes.setBackground(new java.awt.Color(0, 102, 255));
        ambientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ambientes.setForeground(new java.awt.Color(255, 255, 255));
        ambientes.setText("Ambientes del Algoritmo");
        getContentPane().add(ambientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play.png"))); // NOI18N
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 30, 30));

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pause.png"))); // NOI18N
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 30, 30));

        Adelantar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/forward.png"))); // NOI18N
        getContentPane().add(Adelantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 40, 30));

        Atrasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        getContentPane().add(Atrasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 40, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 420, 240));

        AreaAlgoritmo.setColumns(20);
        AreaAlgoritmo.setRows(5);
        jScrollPane3.setViewportView(AreaAlgoritmo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 310, 350));

        algoritmo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        algoritmo.setText("Archivos Algoritmo");
        getContentPane().add(algoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 910, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Controlador.visualizarJuego();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButtonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjecutarActionPerformed
        lexico = new Analizador_Lexico(new BufferedReader(new StringReader(AreaAlgoritmo.getText())));
        sintactico = new A_Sintactico(lexico);

        try {
            sintactico.parse();

            JOptionPane.showMessageDialog(null, "Codigo generado");
            ProcessBuilder processBuilder = new ProcessBuilder();
            processBuilder.command("D:\\app.bat");
            Process process = processBuilder.start();

            System.out.println();
        } catch (Exception e) {
            System.err.println("Error "+e);
        }
    }//GEN-LAST:event_jButtonEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seguimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adelantar;
    private javax.swing.JTextArea AreaAlgoritmo;
    private javax.swing.JTextArea AreaCambioVariables;
    private javax.swing.JButton Atrasar;
    private javax.swing.JLabel algoritmo;
    private javax.swing.JLabel ambientes;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonEjecutar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabeleditor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton play;
    private javax.swing.JButton stop;
    private javax.swing.JLabel variables;
    // End of variables declaration//GEN-END:variables
}
