
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tdcomentario = 65;
  public static final int tprincipal = 7;
  public static final int tcase = 34;
  public static final int tigual = 17;
  public static final int tboolean = 19;
  public static final int tmenorque = 12;
  public static final int tprogram = 6;
  public static final int tvar = 18;
  public static final int tendfor = 45;
  public static final int tor = 40;
  public static final int tuntil = 52;
  public static final int treturn = 54;
  public static final int tcoabre = 25;
  public static final int tdboolean = 62;
  public static final int tif = 28;
  public static final int tdchar = 63;
  public static final int tid = 11;
  public static final int tmenorigual = 13;
  public static final int tentrada = 55;
  public static final int tof = 35;
  public static final int tcall = 59;
  public static final int tdnumber = 60;
  public static final int tsuma = 2;
  public static final int tdefault = 38;
  public static final int tdivision = 5;
  public static final int tint = 20;
  public static final int tbreak = 42;
  public static final int tfor = 43;
  public static final int tmayorigual = 15;
  public static final int tdnumberfloat = 61;
  public static final int tpcoma = 27;
  public static final int tdpuntos = 37;
  public static final int tpabre = 29;
  public static final int tnot = 41;
  public static final int tand = 39;
  public static final int tcoma = 24;
  public static final int tendif = 33;
  public static final int tfunction = 53;
  public static final int EOF = 0;
  public static final int twhile = 49;
  public static final int tinc = 48;
  public static final int error = 1;
  public static final int tto = 46;
  public static final int tendcase = 36;
  public static final int tllcierra = 9;
  public static final int tstring = 23;
  public static final int tfloat = 21;
  public static final int tdstring = 64;
  public static final int tsalida = 57;
  public static final int tdownto = 47;
  public static final int tasignar = 10;
  public static final int telse = 32;
  public static final int tprocedure = 58;
  public static final int tllabre = 8;
  public static final int tthen = 31;
  public static final int tentradasalida = 56;
  public static final int tmayorque = 14;
  public static final int tpcierra = 30;
  public static final int tdo = 44;
  public static final int tmultiplicar = 4;
  public static final int tcocierra = 26;
  public static final int tendwhile = 50;
  public static final int tdiferente = 16;
  public static final int trepeat = 51;
  public static final int tresta = 3;
  public static final int tchar = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tsuma",
  "tresta",
  "tmultiplicar",
  "tdivision",
  "tprogram",
  "tprincipal",
  "tllabre",
  "tllcierra",
  "tasignar",
  "tid",
  "tmenorque",
  "tmenorigual",
  "tmayorque",
  "tmayorigual",
  "tdiferente",
  "tigual",
  "tvar",
  "tboolean",
  "tint",
  "tfloat",
  "tchar",
  "tstring",
  "tcoma",
  "tcoabre",
  "tcocierra",
  "tpcoma",
  "tif",
  "tpabre",
  "tpcierra",
  "tthen",
  "telse",
  "tendif",
  "tcase",
  "tof",
  "tendcase",
  "tdpuntos",
  "tdefault",
  "tand",
  "tor",
  "tnot",
  "tbreak",
  "tfor",
  "tdo",
  "tendfor",
  "tto",
  "tdownto",
  "tinc",
  "twhile",
  "tendwhile",
  "trepeat",
  "tuntil",
  "tfunction",
  "treturn",
  "tentrada",
  "tentradasalida",
  "tsalida",
  "tprocedure",
  "tcall",
  "tdnumber",
  "tdnumberfloat",
  "tdboolean",
  "tdchar",
  "tdstring",
  "tdcomentario"
  };
}

